openapi: 3.1.0
info:
  title: Med Schools
  description: Get a list of med schools and their acceptance rate, average GPA, and average MCAT score, state, etc.
  version: "v1"
servers:
  - url: https://med-schools.fardeem.com/
paths:
  /api/schools:
    post:
      operationId: getSchools
      summary: get a list of med schools and relevant info

      responses:
        "200":
          description: OK
          content:
            text/markdown:
              schema:
                type: string